const translations = {
    en: {
        'home': 'Home',
        'product': 'Product',
        'about-us': 'About Us',
        'price': 'Price',
        'review': 'Review',
        'protect-your-pet': 'PROTECT YOUR PET',
        'monitor-your-pet': 'MONITOR YOUR PETS IN <span>REAL TIME</span>',
        'intro': `PetHealth revolutionises pet care with our innovative smart collar. Monitor your pet's health,
                receive instant alerts and access veterinary services at the click of a button. Join today to
                ensure a healthier and safer future for your furry friend.`,
        'explore-product': 'EXPLORE OUR PRODUCT',
        'health-monitoring': 'Health Monitoring',
        'health-monitoring-desc': `Find out how to monitor your pet's heart rate and temperature in real time to maintain his or her wellbeing.`,
        'preliminary-diagnostics': 'Preliminary Diagnostics',
        'preliminary-diagnostics-desc': `It uses the data collected to obtain preliminary diagnoses and detect potential health problems before they become serious.`,
        'appointment-scheduling': 'Appointment Scheduling',
        'appointment-scheduling-desc': `Schedule appointments with affiliated vets directly from your mobile, sending your pet's health history in advance.`,
        'health-alerts': 'Health Alerts',
        'health-alerts-desc': `Receive immediate alerts if abnormalities in your pet's vital signs are detected, enabling rapid action to be taken.`,
        'join-now': 'Join Now',
        'product-details': 'THE PRODUCT YOU WILL GET HERE',
        'product-details-desc': `Driven by innovation and care for your pet's health, our smart collar is a state-of-the-art solution that
                               combines real-time monitoring with advanced diagnostic technology. Each feature is designed to
                               keep you connected to your pet's well-being and ensure effective health management.`,
        'purchase-product': 'Purchase Product',
        'why-join-us': 'WHY JOIN US?',
        'why-join-us-subheader': `Our diverse user base creates a friendly and supportive environment, where you can connect with other pet owners and stay motivated.`,
        'continuous-monitoring': 'Continuous Monitoring',
        'continuous-monitoring-desc': `Maximise your pet's wellbeing with real-time health monitoring`,
        'veterinary-services': 'Veterinary Services',
        'veterinary-services-desc': `Easily access veterinary services and schedule appointments from the app`,
        'our-plans': 'OUR PLANS',
        'our-plans-subheader': `Explore our subscription plans, each designed to offer the best care and monitoring for your pet.`,
        'basic-plan': 'Basic',
        'basic-plan-feature1': 'Physical activity monitoring',
        'basic-plan-feature2': 'Basic health alerts',
        'basic-plan-feature3': 'Weekly health reports',
        'basic-plan-feature4': 'Smart Collar',
        'premium-plan': 'Premium',
        'premium-plan-feature1': 'Real-time health monitoring',
        'premium-plan-feature2': 'Detailed health alerts',
        'premium-plan-feature3': 'Behavioural analysis',
        'premium-plan-feature4': 'Online veterinary access',
        'premium-plan-feature5': 'Smart Collar',
        'ultimate-plan': 'Ultimate',
        'ultimate-plan-feature1': 'All the benefits of Premium',
        'ultimate-plan-feature2': 'Advanced monitoring with diagnostics',
        'ultimate-plan-feature3': 'Integration with affiliated veterinarians',
        'ultimate-plan-feature4': '24/7 emergency service',
        'ultimate-plan-feature5': 'Personalised health reports',
        'ultimate-plan-feature6': 'Smart Collar',
        'review-title': 'RESEÑA',
        'review-content': `"Using this collar has completely transformed the way I care for my cat. The sensors are incredibly accurate
                        and it's reassuring to know that I can monitor his health at any time. The best thing is receiving immediate
                        alerts if something is wrong, which has helped us prevent emergency situations more than once."`,
        'reviewer-name': 'Rosy',
        'reviewer-role': 'Cat Owner',
        'footer-intro': `Take the first step towards healthier and safer care for your pet with our unbeatable price plans.
                       Take care, protect and improve the health of your best friend!`,
        'footer-company': 'Company',
        'footer-business': 'Business',
        'footer-franchises': 'Franchises',
        'footer-partnerships': 'Partnerships',
        'footer-vet-network': 'Veterinary Care Network',
        'footer-about-us': 'About us',
        'footer-blog': 'Blog',
        'footer-security': 'Security',
        'footer-team': 'Our Team',
        'footer-contact': 'Contact',
        'footer-contact-us': 'Contact us',
        'footer-privacy': 'Privacy Policy',
        'footer-terms': 'Terms & Conditions',
        'footer-calculator': 'Pet Health Calculator'
    },
    es: {
        'home': 'Inicio',
        'product': 'Producto',
        'about-us': 'Sobre Nosotros',
        'price': 'Precio',
        'review': 'Reseña',
        'protect-your-pet': 'PROTEGE A TU MASCOTA',
        'monitor-your-pet': 'MONITOREA A TUS MASCOTAS EN <span>TIEMPO REAL</span>',
        'intro': `PetHealth revoluciona el cuidado de las mascotas con nuestro innovador collar inteligente. Monitorea la salud de tu mascota,
                recibe alertas instantáneas y accede a servicios veterinarios con solo un clic. Únete hoy para
                asegurar un futuro más saludable y seguro para tu amigo peludo.`,
        'explore-product': 'EXPLORA NUESTRO PRODUCTO',
        'health-monitoring': 'Monitoreo de Salud',
        'health-monitoring-desc': `Descubre cómo monitorear la frecuencia cardíaca y la temperatura de tu mascota en tiempo real para mantener su bienestar.`,
        'preliminary-diagnostics': 'Diagnósticos Preliminares',
        'preliminary-diagnostics-desc': `Utiliza los datos recopilados para obtener diagnósticos preliminares y detectar posibles problemas de salud antes de que se vuelvan graves.`,
        'appointment-scheduling': 'Programación de Citas',
        'appointment-scheduling-desc': `Programa citas con veterinarios afiliados directamente desde tu móvil, enviando el historial de salud de tu mascota por adelantado.`,
        'health-alerts': 'Alertas de Salud',
        'health-alerts-desc': `Recibe alertas inmediatas si se detectan anomalías en los signos vitales de tu mascota, permitiendo una acción rápida.`,
        'join-now': 'Únete Ahora',
        'product-details': 'EL PRODUCTO QUE OBTENDRÁS AQUÍ',
        'product-details-desc': `Impulsado por la innovación y el cuidado de la salud de tu mascota, nuestro collar inteligente es una solución de última generación que combina el monitoreo en tiempo real con tecnología de diagnóstico avanzada. Cada característica está diseñada para mantenerte conectado con el bienestar de tu mascota y asegurar una gestión eficaz de la salud.`,
        'purchase-product': 'Comprar Producto',
        'why-join-us': '¿POR QUÉ UNIRSE A NOSOTROS?',
        'why-join-us-subheader': `Nuestra diversa base de usuarios crea un ambiente amigable y de apoyo, donde puedes conectar con otros dueños de mascotas y mantenerte motivado.`,
        'continuous-monitoring': 'Monitoreo Continuo',
        'continuous-monitoring-desc': `Maximiza el bienestar de tu mascota con monitoreo de salud en tiempo real`,
        'veterinary-services': 'Servicios Veterinarios',
        'veterinary-services-desc': `Accede fácilmente a servicios veterinarios y programa citas desde la aplicación`,
        'our-plans': 'NUESTROS PLANES',
        'our-plans-subheader': `Explora nuestros planes de suscripción, cada uno diseñado para ofrecer el mejor cuidado y monitoreo para tu mascota.`,
        'basic-plan': 'Básico',
        'basic-plan-feature1': 'Monitoreo de actividad física',
        'basic-plan-feature2': 'Alertas de salud básicas',
        'basic-plan-feature3': 'Informes de salud semanales',
        'basic-plan-feature4': 'Collar Inteligente',
        'premium-plan': 'Premium',
        'premium-plan-feature1': 'Monitoreo de salud en tiempo real',
        'premium-plan-feature2': 'Alertas de salud detalladas',
        'premium-plan-feature3': 'Análisis de comportamiento',
        'premium-plan-feature4': 'Acceso veterinario en línea',
        'premium-plan-feature5': 'Collar Inteligente',
        'ultimate-plan': 'Ultimate',
        'ultimate-plan-feature1': 'Todos los beneficios de Premium',
        'ultimate-plan-feature2': 'Monitoreo avanzado con diagnósticos',
        'ultimate-plan-feature3': 'Integración con veterinarios afiliados',
        'ultimate-plan-feature4': 'Servicio de emergencia 24/7',
        'ultimate-plan-feature5': 'Informes de salud personalizados',
        'ultimate-plan-feature6': 'Collar Inteligente',
        'review-title': 'RESEÑA',
        'review-content': `"Usar este collar ha transformado completamente la forma en que cuido a mi gato. Los sensores son increíblemente precisos
                        y es reconfortante saber que puedo monitorear su salud en cualquier momento. Lo mejor es recibir alertas inmediatas
                        si algo anda mal, lo que nos ha ayudado a prevenir situaciones de emergencia más de una vez."`,
        'reviewer-name': 'Rosy',
        'reviewer-role': 'Dueña de Gato',
        'footer-intro': `Da el primer paso hacia un cuidado más saludable y seguro para tu mascota con nuestros planes de precios inmejorables.
                       ¡Cuida, protege y mejora la salud de tu mejor amigo!`,
        'footer-company': 'Compañía',
        'footer-business': 'Negocios',
        'footer-franchises': 'Franquicias',
        'footer-partnerships': 'Colaboraciones',
        'footer-vet-network': 'Red de Cuidado Veterinario',
        'footer-about-us': 'Sobre Nosotros',
        'footer-blog': 'Blog',
        'footer-security': 'Seguridad',
        'footer-team': 'Nuestro Equipo',
        'footer-contact': 'Contacto',
        'footer-contact-us': 'Contáctanos',
        'footer-privacy': 'Política de Privacidad',
        'footer-terms': 'Términos y Condiciones',
        'footer-calculator': 'Calculadora de Salud para Mascotas'
    }
};

function changeLanguage(language) {
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        element.innerHTML = translations[language][key];
    });
}

// Set default language to English
changeLanguage('en');
